### ISSUE TITLE
Use a more specific name

### ISSUE THREAD

**Issue by markwalet** [nsaumini/nova-field-count#2]
I love the idea of small extensions like this. The only thing I am worried about it the use of `Count` as a class name.

A lot of developer really like a more specific names. It helps with autocompletion, it prevents naming collissions, etc.

Maybe you could rename the `Count` class to something like `EloquentRelationCount` or maybe just `RelationCount` would be sufficient.

**Comment by nsaumini** [comment]
Noted. Renamed class name to `RelationshipCount`. Thanks
