### ISSUE TITLE
Add sortable() support

### ISSUE THREAD

**Issue by goyote** [nsaumini/nova-field-count#3]
Thanks for making this, would be nice if it had sortable() support

**Comment by vhkhb** [comment]
I am also looking for the same thing.

**Comment by nsaumini** [comment]
Overwrite the `indexQuery` in the resource as below

    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->withCount('comments as comments'); // Relationship name as alias
    } 

Also add `sortable` support in the field `RelationshipCount::make('Comments Count', 'comments')->sortable()`
